version: '3'

services: 
    app:
        container_name: encoder
        build: .
        volumes: 
            - .:/go/src/
        networks:
            - encoder

    gcs:
        container_name: fake
        image: fsouza/fake-gcs-server
        ports:
            - "4443:4443"
        volumes:
            - ./examples/data:/data
        networks:
            - encoder


networks:
  encoder: